# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('is_winner', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=1000, null=True)),
                ('project_id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(null=True)),
                ('thumbnail', models.URLField(null=True)),
                ('details', models.TextField(null=True)),
                ('pitch', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('projects', models.ManyToManyField(related_name='technologies', to='hackathon.Project')),
            ],
        ),
    ]
