# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
    ]
