# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
